language: cpp
compiler: gcc
sudo: false
addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8 
      - g++-4.8
      - gcov-4.6
      - clang
      - doxygen
      - valgrind
      - libgtest-dev
      - libboost-dev

before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++ --version 2>&1 | grep g++
    - gcov --version | grep gcov
    - valgrind --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen --version

install: 
    # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - cd -

script:
    - ls -al